---
title: 建構子的初始化Exception
date: 2014-06-24T11:55:00.000+08:00
tags: 
- C_and_Cpp

categories:
- 舊部落格移植文章
---

# 建構子的初始化Exception

原文連結: https://darkblack01.blogspot.com/2014/06/exception.html
移植時的最後更新日期: 2015-12-23T14:16:57.710+08:00

開門見山，以這樣的類別為例：<br /><br /><pre class="prettyprint"><code>class foo{<br />    int i;<br />    char c;<br />public:<br />    foo();  //建構子<br />};</code></pre>一般來說，我們的建構子都這樣寫 <br /><pre class="prettyprint"><code>foo::foo()<br />:i(0), c(''){  &lt;-- 建構初始列<br />}</code></pre>但是，如果想在建構子上加try-catch，難道是這樣？？ <br /><pre class="prettyprint"><code>foo::foo()<br />:i(0), c(''){  &lt;-- 建構初始列<br />    try{<br />    }<br />    catch(...){<br />    }<br />}</code></pre>發現了嗎？<strike>那捕捉個屁呀？</strike>跟本就是把擸物放在網子外。<br />唷！不！所謂江湖一點訣！<br />在Primer C++中就有介紹，如果要捕捉到建構初始列上，初始化成員變數時的exception時，就一定要這樣寫<br /><pre class="prettyprint"><code>foo::foo()<br />try:i(0), c(''){  &lt;-- 建構初始列<br />    <br />}catch(...)<br />{    }</code></pre>這個名稱叫「function try block」<br /><br />看到這，會想知道解構子怎麼處理嗎？<br /><br />解構子.....基本上，絕對不可以出現exception!!!!
